USE regalonatural; DELETE FROM regalonatural.ps_customization_field_lang;
INSERT INTO `ps_customization_field_lang` VALUES (1,5,1,'Imagen para personalizar');
INSERT INTO `ps_customization_field_lang` VALUES (2,5,1,'Palabra a construir (sólo Mayúsculas) Max: 9 letras');
INSERT INTO `ps_customization_field_lang` VALUES (3,5,1,'Adjunta aquí tu foto (Max. 8Mb)');
INSERT INTO `ps_customization_field_lang` VALUES (4,5,1,'Nombre');
INSERT INTO `ps_customization_field_lang` VALUES (5,5,1,'Fecha Evento');
INSERT INTO `ps_customization_field_lang` VALUES (6,5,1,'Nombre');
INSERT INTO `ps_customization_field_lang` VALUES (7,5,1,'Fecha Evento');
INSERT INTO `ps_customization_field_lang` VALUES (8,5,1,'Foto');
INSERT INTO `ps_customization_field_lang` VALUES (9,5,1,'Foto Num-1');
INSERT INTO `ps_customization_field_lang` VALUES (10,5,1,'Foto Num-2');
INSERT INTO `ps_customization_field_lang` VALUES (11,5,1,'Foto Num-3');
INSERT INTO `ps_customization_field_lang` VALUES (12,5,1,'Foto Num-4');
INSERT INTO `ps_customization_field_lang` VALUES (13,5,1,'Foto Num-1');
INSERT INTO `ps_customization_field_lang` VALUES (14,5,1,'Foto Num-2');
INSERT INTO `ps_customization_field_lang` VALUES (15,5,1,'Foto Num-3');
INSERT INTO `ps_customization_field_lang` VALUES (16,5,1,'Foto Num-4');
INSERT INTO `ps_customization_field_lang` VALUES (17,5,1,'Nombre');
INSERT INTO `ps_customization_field_lang` VALUES (18,5,1,'Fecha Evento');
INSERT INTO `ps_customization_field_lang` VALUES (20,5,1,'Texto:');
INSERT INTO `ps_customization_field_lang` VALUES (21,5,1,'Fecha Evento:');
INSERT INTO `ps_customization_field_lang` VALUES (23,5,1,'Texto:');
INSERT INTO `ps_customization_field_lang` VALUES (24,5,1,'Fecha Evento:');
INSERT INTO `ps_customization_field_lang` VALUES (25,5,1,'Nombre');
INSERT INTO `ps_customization_field_lang` VALUES (26,5,1,'Fecha Evento');
