USE regalonatural; DELETE FROM regalonatural.ps_order_return_state_lang;
INSERT INTO `ps_order_return_state_lang` VALUES (1,1,'A la espera de confirmación');
INSERT INTO `ps_order_return_state_lang` VALUES (1,2,'Waiting for confirmation');
INSERT INTO `ps_order_return_state_lang` VALUES (1,3,'Waiting for confirmation');
INSERT INTO `ps_order_return_state_lang` VALUES (1,4,'Waiting for confirmation');
INSERT INTO `ps_order_return_state_lang` VALUES (1,5,'In asteptarea confirmarii');
INSERT INTO `ps_order_return_state_lang` VALUES (1,6,'Waiting for confirmation');
INSERT INTO `ps_order_return_state_lang` VALUES (2,1,'A la espera del paquete');
INSERT INTO `ps_order_return_state_lang` VALUES (2,2,'Waiting for package');
INSERT INTO `ps_order_return_state_lang` VALUES (2,3,'Waiting for package');
INSERT INTO `ps_order_return_state_lang` VALUES (2,4,'Waiting for package');
INSERT INTO `ps_order_return_state_lang` VALUES (2,5,'In asteptarea pachetului');
INSERT INTO `ps_order_return_state_lang` VALUES (2,6,'Waiting for package');
INSERT INTO `ps_order_return_state_lang` VALUES (3,1,'Paquete recibido');
INSERT INTO `ps_order_return_state_lang` VALUES (3,2,'Package received');
INSERT INTO `ps_order_return_state_lang` VALUES (3,3,'Package received');
INSERT INTO `ps_order_return_state_lang` VALUES (3,4,'Package received');
INSERT INTO `ps_order_return_state_lang` VALUES (3,5,'Pachetul a fost receptionat');
INSERT INTO `ps_order_return_state_lang` VALUES (3,6,'Package received');
INSERT INTO `ps_order_return_state_lang` VALUES (4,1,'Devolución denegada');
INSERT INTO `ps_order_return_state_lang` VALUES (4,2,'Return denied');
INSERT INTO `ps_order_return_state_lang` VALUES (4,3,'Return denied');
INSERT INTO `ps_order_return_state_lang` VALUES (4,4,'Return denied');
INSERT INTO `ps_order_return_state_lang` VALUES (4,5,'Returnare anulata');
INSERT INTO `ps_order_return_state_lang` VALUES (4,6,'Return denied');
INSERT INTO `ps_order_return_state_lang` VALUES (5,1,'Devolución completada');
INSERT INTO `ps_order_return_state_lang` VALUES (5,2,'Return completed');
INSERT INTO `ps_order_return_state_lang` VALUES (5,3,'Return completed');
INSERT INTO `ps_order_return_state_lang` VALUES (5,4,'Return completed');
INSERT INTO `ps_order_return_state_lang` VALUES (5,5,'Returnare completa');
INSERT INTO `ps_order_return_state_lang` VALUES (5,6,'Return completed');
